### ISSUE TITLE
Getting Success spelling incorrect when triggering notifications

### ISSUE THREAD

**Issue by preethi-fission** [javiern8410/actions-google-chat-notification#101]
While triggering notifications from github actions the  success spelling is not displaying correctly 
Refer the below screenshot.
**![Screenshot from 2024-06-04 21-49-51](https://github.com/javiern8410/actions-google-chat-notification/assets/133639452/dac92a3f-331c-4075-b9ab-0410aaacc845)**

I found the issue in the below  **dist/main.js** file 

![image](https://github.com/javiern8410/actions-google-chat-notification/assets/133639452/79d417d7-f328-46fc-9481-5d3e12ab0811).

Kindly make the changes in the above mentioned file if possible

**Comment by javiern8410** [comment]
Thank you for reporting this issue, I will fix it quickly.
