### ISSUE TITLE
Error with v1.0.4 tag

### ISSUE THREAD

**Issue by preethi-fission** [javiern8410/actions-google-chat-notification#103]
@javiern8410 , when using v1.0.4 google chat notifications in github actions we are getting the below error
<img width="1023" alt="Screenshot 2024-07-30 at 10 42 29 AM" src="https://github.com/user-attachments/assets/397b088e-6c42-4897-a7e0-03a04608b522">

**Comment by javiern8410** [comment]
I am releasing a new version to fix it, please use it. Thanks for reporting this bug.
